#pragma once

#define BPX_SDK_PROJECT_NAME "bpx_sdk"
#define BPX_SDK_PROJECT_VERSION "1.0.7"
#define BPX_SDK_VERSION_MAJOR 1
#define BPX_SDK_VERSION_MINOR 0
#define BPX_SDK_VERSION_PATCH 7
#define BPX_SDK_GIT_COMMIT_HASH "6d4c11b"
